apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce
data:
  MYSQL_DATABASE: orderservice
  PRODUCT_DB_URL: jdbc:postgresql://postgres:5432/ecomdb
  ORDER_DB_URL: jdbc:mysql://mysql:3306/orderservice
  MONGO_URI: mongodb://mongo:27017/userdb
  KEYCLOAK_SERVER_URL: http://keycloak:8080
  SPRING_RABBITMQ_HOST: rabbitmq
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS: classpath:/config
