apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
type: Opaque
stringData:
  POSTGRES_USER: sasha
  POSTGRES_PASSWORD: ecom_password
  PRODUCT_DB_USER: sasha
  PRODUCT_DB_PASSWORD: ecom_password
  MYSQL_ROOT_PASSWORD: ecom_root_password
  DB_USER: root
  DB_PASSWORD: ecom_root_password
  KEYCLOAK_ADMIN_USERNAME: admin
  KEYCLOAK_ADMIN_PASSWORD: admin
  KEYCLOAK_SERVICE_USERNAME: admin
  KEYCLOAK_SERVICE_PASSWORD: admin
  KEYCLOAK_CLIENT_UID: replace-with-keycloak-client-uuid
  SPRING_RABBITMQ_USERNAME: guest
  SPRING_RABBITMQ_PASSWORD: guest
