spring:
  application:
    name: user-service
#  mongodb:
#      uri: ${MONGO_URI}
  data:
    mongodb:
      uri: mongodb://mongo:27017/userdb
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
server:
  port: 8082



logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            logging=DEBUG:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.mongodb.driver: DEBUG
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-history: 7
      max-file-size: 5MB

management:
  health:
    mongodb:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    shutdown:
      enabled: false
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
    register-with-eureka: true
    fetch-registry: true


# KEYCLOAK



keycloak:
  admin:
    username: ${KEYCLOAK_SERVICE_USERNAME}
    password: ${KEYCLOAK_SERVICE_PASSWORD}
    server-url: ${KEYCLOAK_SERVER_URL:http://keycloak:8080}
    realm: ecom-app
    client-id: admin-cli
    client-uid: ${KEYCLOAK_CLIENT_UID}
