spring:
  application:
    name: configserver
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
  cloud:
    config:
      server:
        native:
          search-locations: ${SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS:file:///F:\eCommerce Microservices\configserver\src\main\resources\config}


server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
